### PR TITLE
fix: update podspec and Package.swift

### PR DESCRIPTION
**Pull request by nicolasjuarezn**
Solves the issue: https://github.com/UPcload/FitAnalytics-WebWidget-iOS/issues/18#issue-2083522349

### CODE REVIEW

**Review by ZahraMammadli — APPROVED** [review]
LGTM

**Comment by mattiacantalu** [comment]
I discovered an issue with `Package` integration.. I'm not able to intefrate the widget again.

Does it happens even for you guys?

image

**Comment by nicolasjuarezn** [comment]
> @ZahraMammadli @nicolasjuarezn I discovered an issue with `Package` integration.. I'm not able to intefrate the widget again.
> 
> Does it happens even for you guys?
> 
> image

Hey @mattiacantalu , perhaps you were using the fork from https://github.com/UPcload/FitAnalytics-WebWidget-iOS/pull/16? It seems like we never supported SPM, the whole project is set to work with cocoapods. 

We can update in the future this project to properly support SPM, but I can't guarantee due dates. 

Also, the change on this PR did not change any existing behavior.

**Comment by mattiacantalu** [comment]
@nicolasjuarezn I'm not using the fork version due the lack of the privacy manifest and other _latest_ updates.
We integrated the v 0.5.2 manually without CocoaPods (we dont have it).

AFAIK the `Package.swift` has been added to the repo (in the past), so it supposes to be compatible (but actually it doesnt).

**Comment by nicolasjuarezn** [comment]
@mattiacantalu FYI addressing a lot of issues here: https://github.com/UPcload/FitAnalytics-WebWidget-iOS/pull/24

**Pull request merged**
